"""Compile a discharge summary from a case record.

**Nothing here is generated by a model, and that is the point.** A discharge
summary is a clinical document that follows the patient out of the hospital; a
plausible-sounding sentence that is not in the record is exactly the failure
mode to design out. So every clinical line below is copied from a field, or
computed arithmetically from recorded observations, and anything absent is
rendered as an explicit "not recorded" rather than smoothed over.

The two free-text sections — follow-up plan and discharge destination — are
typed by the clinician. They are the only prose in the document, and a human
wrote them.

``compile_summary`` returns a plain dict, which is stored on the summary row as
a snapshot. A signed summary must keep saying what was signed even if the case
record changes afterwards.
"""
from __future__ import annotations

from datetime import date, datetime, timezone
from typing import Any

from app import models
from app.scoring import RESPONSE

NOT_RECORDED = "Not recorded"


def _iso(value: date | datetime | None) -> str | None:
    """Timestamps are stored as ISO strings.

    The snapshot is a JSON column, and a plain-text timestamp keeps it portable
    and stable — a signed document should not depend on how this process happens
    to serialise dates. Templates format it back with the ``when`` filter.
    """
    return value.isoformat() if value is not None else None

# Only these observation fields are quoted back, and only when present.
VITALS_LABELS = (
    ("respiratory_rate", "Respiratory rate", "/min"),
    ("spo2", "SpO₂", "%"),
    ("systolic_bp", "Systolic BP", "mmHg"),
    ("pulse", "Pulse", "bpm"),
    ("temperature_c", "Temperature", "°C"),
)


def _text(value: str | None) -> str:
    value = (value or "").strip()
    return value or NOT_RECORDED


def _contact(name: str | None, phone: str | None) -> str:
    parts = [p.strip() for p in (name, phone) if p and p.strip()]
    return " · ".join(parts) if parts else NOT_RECORDED


def _listing(values: list | None, empty: str = NOT_RECORDED) -> list[str]:
    if not values:
        return [empty]
    return [str(v).strip() for v in values if str(v).strip()] or [empty]


def _length_of_stay(admitted: date | None, discharged: date | None) -> str:
    if admitted is None:
        return NOT_RECORDED
    end = discharged or datetime.now(timezone.utc).date()
    days = (end - admitted).days
    if days < 0:
        # Refuse to state a negative stay; the dates disagree and a human must look.
        return f"Dates inconsistent (admitted {admitted}, discharged {discharged})"
    if days == 0:
        return "Same-day"
    return f"{days} day{'s' if days != 1 else ''}"


def _medications(case: models.CaseRecord) -> list[str]:
    lines = []
    for med in case.medications or []:
        if not isinstance(med, dict) or not med.get("name"):
            continue
        parts = [med["name"]]
        for key in ("dose", "route", "frequency"):
            if med.get(key):
                parts.append(str(med[key]))
        lines.append(" ".join(parts))
    return lines or ["None recorded"]


def _observation_course(case: models.CaseRecord) -> dict[str, Any]:
    """The NEWS2 trajectory, computed from what was actually recorded."""
    scored = [o for o in case.observations if o.news2_score is not None]
    if not scored:
        return {
            "recorded": 0,
            "narrative": "No scored observations were recorded during this admission.",
            "first": None, "last": None, "peak": None, "final_vitals": [],
        }

    # case.observations is newest-first.
    chronological = list(reversed(scored))
    first, last = chronological[0], chronological[-1]
    peak = max(scored, key=lambda o: o.news2_score)

    direction = (
        "unchanged" if last.news2_score == first.news2_score
        else "improved" if last.news2_score < first.news2_score
        else "deteriorated"
    )
    narrative = (
        f"{len(scored)} scored observation{'s' if len(scored) != 1 else ''} recorded. "
        f"NEWS2 {direction} from {first.news2_score} on admission to {last.news2_score} "
        f"at the last round, peaking at {peak.news2_score}."
    )

    final_vitals = []
    for attr, label, unit in VITALS_LABELS:
        value = getattr(last, attr)
        if value is not None:
            final_vitals.append(f"{label} {value} {unit}".strip())
    if last.on_oxygen:
        final_vitals.append("on supplemental oxygen")

    def snapshot(obs) -> dict:
        return {
            "at": _iso(obs.recorded_at),
            "score": obs.news2_score,
            "risk": obs.risk_level,
            "by": obs.recorded_by,
        }

    return {
        "recorded": len(scored),
        "narrative": narrative,
        "first": snapshot(first),
        "last": snapshot(last),
        "peak": snapshot(peak),
        "final_vitals": final_vitals,
        "escalation": RESPONSE.get(last.risk_level or "", ""),
    }


def _escalations(case: models.CaseRecord) -> list[dict]:
    """Alerts raised during the admission, newest last."""
    return [
        {
            "at": _iso(alert.created_at),
            "severity": alert.severity,
            "message": alert.message,
            "acknowledged_by": alert.acknowledged_by,
            "acknowledged_at": _iso(alert.acknowledged_at),
        }
        for alert in reversed(case.alerts)
    ]


def _notes(case: models.CaseRecord) -> list[dict]:
    return [
        {
            "at": _iso(note.created_at),
            "kind": note.kind.value,
            "author": note.author_name,
            "role": note.author_role,
            "body": note.body,
            "situation": note.situation,
            "background": note.background,
            "assessment": note.assessment,
            "recommendation": note.recommendation,
            "outstanding": note.outstanding or [],
        }
        for note in reversed(case.clinical_notes)
    ]


def _outstanding(case: models.CaseRecord) -> list[str]:
    """Tasks handed over and never marked done — they follow the patient out."""
    tasks: list[str] = []
    for note in reversed(case.clinical_notes):
        for task in note.outstanding or []:
            if task not in tasks:
                tasks.append(task)
    return tasks


def compile_summary(case: models.CaseRecord) -> dict[str, Any]:
    """Build the summary content. Every value is copied or computed, never inferred."""
    patient = case.patient
    return {
        "compiled_at": _iso(datetime.now(timezone.utc)),
        "provenance": (
            "Compiled automatically from the case record. Every clinical entry is copied "
            "from the record or computed from recorded observations; nothing is inferred. "
            "Fields left blank in the record appear as 'Not recorded'."
        ),
        "patient": {
            "full_name": patient.full_name,
            "mrn": _text(patient.mrn),
            "date_of_birth": _iso(patient.date_of_birth),
            "age_years": patient.age_years,
            "sex": patient.sex.value,
            "address": _text(patient.address),
            # One line, so an unrecorded kin does not read "Not recorded Not recorded".
            "next_of_kin": _contact(patient.next_of_kin, patient.next_of_kin_phone),
        },
        "admission": {
            "case_number": case.case_number,
            "ward": _text(case.ward_name),
            "bed": _text(case.bed_label),
            "admitted": _iso(case.admission_date),
            "discharged": _iso(case.discharge_date),
            "length_of_stay": _length_of_stay(case.admission_date, case.discharge_date),
            "consultant": _text(case.consultant),
            "department": _text(case.department),
            "status": case.status.value,
        },
        "clinical": {
            "presenting_complaint": _text(case.chief_complaint),
            "diagnosis": _text(case.provisional_diagnosis),
            "history": _text(case.history),
            "comorbidities": _listing(case.comorbidities, "None recorded"),
            "allergies": _listing(case.allergies, "None recorded"),
            "medications": _medications(case),
            "record_notes": _text(case.notes),
        },
        "course": _observation_course(case),
        "escalations": _escalations(case),
        "notes": _notes(case),
        "outstanding": _outstanding(case),
        "verification": {
            "status": case.verification.value,
            "verified_by": case.verified_by,
            "verified_at": _iso(case.verified_at),
            # A summary built off an unverified transcription must say so.
            "caveat": (
                None if case.verification == models.VerificationStatus.verified
                else "This case record has not been verified against the original case sheet."
            ),
        },
    }
